# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ConversionC13Celsius.py
# Created on: 2019-11-18 16:59:02.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ConversionC13Celsius
# ---------------------------------------------------------------------------

# Import arcpy module
import sys, os
import arcpy
from arcpy.sa import *

# Esri end of added imports

# Check out any necessary licenses  
arcpy.CheckOutExtension("spatial") 

# Local variables:  
#ws = r"C:\prueba"
#wsout = r"C:\prueba\temporal" 


ws =r'C:\Users\jaunta\Documents\proy\ideam'
wsout =r'C:\Users\jaunta\Documents\proy\ideam\images'

"%scratchFolder%\\%Name%"
ws = u'/u01/Data/GOES/Temporal/GOES/C08'
#wsout = u'/u01/Data/Servicios/scratch'
wsout = u'/u01/Data/Servicios/scratch'

# Process: Iterate Rasters  
arcpy.env.workspace = ws  

rasterlist = arcpy.ListRasters("*","tif")
print rasterlist  
for ras_name in rasterlist:
	
	raster = Raster(ras_name)	
	#ras_name_float = arcpy.sa.Float(Raster(ras_name))
	ras_extend = raster.extent
	print ras_extend
	ras_cellsize = (raster.meanCellHeight + raster.meanCellWidth) / 2
	print ras_cellsize


	constant1 = 0.042249858
	constant2 = 138.5
	constant3 = 273.5

	#calculo
	#result1 = arcpy.sa.Float(Times(ras_name_float, constant1))
	
	result1 = Times(raster, constant1)
	result2 = Plus(constant2, result1)
	resultf = Minus(result2, constant3)
	resultf.save(os.path.join(wsout, ras_name))

print('Done Processing')
